CREATE EXTERNAL TABLE `imel_nl70_at_container_history`(
  `id` int, 
  `transactioncontext` string, 
  `transactioncode` string, 
  `hostmovementcode` string, 
  `container` string, 
  `incontainer` string, 
  `containerclassid` int, 
  `incontainerclassid` int, 
  `srcproductid` int, 
  `dstproductid` int, 
  `srcproductno` string, 
  `dstproductno` string, 
  `oldquantity` decimal(28,10), 
  `newquantity` decimal(28,10), 
  `quantityadjusted` decimal(28,10), 
  `oldqtyalloc` decimal(28,10), 
  `newqtyalloc` decimal(28,10), 
  `quantityallocated` decimal(28,10), 
  `uomcode` string, 
  `srcinventorystatus` int, 
  `dstinventorystatus` int, 
  `srcwarehouselocationid` int, 
  `dstwarehouselocationid` int, 
  `srcwarehouselocation` string, 
  `dstwarehouselocation` string, 
  `srcwarehouse` string, 
  `dstwarehouse` string, 
  `srclotno` string, 
  `dstlotno` string, 
  `srcpartnerlotno` string, 
  `dstpartnerlotno` string, 
  `sapbatchmanaged` boolean, 
  `srcpartnerid` int, 
  `dstpartnerid` int, 
  `srcgradeid` int, 
  `dstgradeid` int, 
  `orderno` string, 
  `orderlineno` int, 
  `ordertype` int, 
  `wiporderno` string, 
  `wipordertype` int, 
  `referenceid` int, 
  `lastupdateon` timestamp, 
  `lastupdatedby` string, 
  `createdon` timestamp, 
  `createdby` string, 
  `active` boolean, 
  `lastdeleteon` timestamp, 
  `lastdeletedby` string, 
  `lastreactivateon` timestamp, 
  `lastreactivatedby` string, 
  `archiveid` int, 
  `lastarchiveon` timestamp, 
  `lastarchivedby` string, 
  `lastrestoreon` timestamp, 
  `lastrestoredby` string, 
  `rowversionstamp` int, 
  `sealnumber` string, 
  `sealeddate` string, 
  `brokendate` string)
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat'
LOCATION
  's3://daas-s3-raw-dev/imel/imel_nl70/imel_nl70_at_container_history/'
TBLPROPERTIES (
  'CrawlerSchemaDeserializerVersion'='1.0', 
  'CrawlerSchemaSerializerVersion'='1.0', 
  'UPDATED_BY_CRAWLER'='daas-imel-nl70', 
  'averageRecordSize'='169', 
  'classification'='parquet', 
  'compressionType'='none', 
  'objectCount'='7', 
  'recordCount'='211', 
  'sizeKey'='71160', 
  'typeOfData'='file')